#!/bin/sh
set -e

cat << EOF > /app/dist/config.js
window._env_ = {
  VITE_HOST_ENV: "${HOST_ENV}",
  VITE_VERSION: "${VERSION}",
  VITE_CONTROL_PANEL_API: "${CONTROL_PANEL_API}",
  VITE_VIEWER_API: "${VIEWER_API}",
  VITE_VIEWER_JWT_KEY: "${VIEWER_JWT_KEY}",
  VITE_GOOGLE_MAPS_KEY: "${GOOGLE_MAPS_KEY}",
  VITE_PUBLIC_POSTHOG_KEY: "${PUBLIC_POSTHOG_KEY}",
  VITE_GA_TRACKING_ID: "${GA_TRACKING_ID}",
  VITE_MIXPANEL_KEY: "${MIXPANEL_KEY}",
  VITE_HOSTNAME_PARTS: "${HOSTNAME_PARTS}",
  VITE_SWAP_CP: "${SWAP_CP}",
  VITE_VIEWER_PAGE_SUBDOMAIN: "${VIEWER_PAGE_SUBDOMAIN}",
  VITE_GITHUB_JS_PATH: "${GITHUB_JS_PATH}",
  VITE_CDN_JS_PATH: "${CDN_JS_PATH}",
  VITE_SOCIAL_META: "${SOCIAL_META}"
};
EOF

exec "$@"